-- Generated by `terrain-fetch --emit-lua`. Do not edit by hand:
-- regenerate it whenever a heightmap is rebuilt, so the in-game
-- scale always matches the PNG that was imported.
--
-- baseElevationM is what pure black means; every level of the 16-bit
-- heightmap adds metersPerLevel. studsPerMeterY converts metres to studs.

local Mountains = {}

Mountains.order = {"aconcagua", "beskydy", "everest", "kilimanjaro", "longspeak", "montblanc"}

Mountains.byKey = {
	["aconcagua"] = {
		name = "Aconcagua",
		continent = "South America",
		peak = "Aconcagua",
		peakElevationM = 6961,
		minElevationM = 1917,
		maxElevationM = 6940,
		reliefM = 5023,
		widthM = 46800.6,
		heightM = 55672.1,
		regionSize = Vector3.new(16384, 602.8, 19489.8),
		regionPosition = Vector3.new(0, 301.4, 0),
		studsPerMeterXZ = 0.3501,
		studsPerMeterY = 0.12,
		baseElevationM = 1917,
		terrainHeightStuds = 602.8,
		verticalExaggeration = 0.3428,
		heightmap = "aconcagua.png",
		placeId = 0, -- set PlaceID in presets.go once the Place is published
	},
	["beskydy"] = {
		name = "Beskydy",
		continent = "Europe",
		peak = "Lysa hora",
		peakElevationM = 1323,
		minElevationM = 278,
		maxElevationM = 1314,
		reliefM = 1036,
		widthM = 39763.1,
		heightM = 33409,
		regionSize = Vector3.new(16384, 466, 13765.8),
		regionPosition = Vector3.new(0, 233, 0),
		studsPerMeterXZ = 0.412,
		studsPerMeterY = 0.45,
		baseElevationM = 278.2,
		terrainHeightStuds = 466,
		verticalExaggeration = 1.0921,
		heightmap = "beskydy.png",
		placeId = 0, -- set PlaceID in presets.go once the Place is published
	},
	["everest"] = {
		name = "Everest",
		continent = "Asia",
		peak = "Mount Everest",
		peakElevationM = 8849,
		minElevationM = 2950,
		maxElevationM = 8753,
		reliefM = 5803,
		widthM = 49155.4,
		heightM = 33423,
		regionSize = Vector3.new(16384, 580.3, 11140.2),
		regionPosition = Vector3.new(0, 290.2, 0),
		studsPerMeterXZ = 0.3333,
		studsPerMeterY = 0.1,
		baseElevationM = 2950,
		terrainHeightStuds = 580.3,
		verticalExaggeration = 0.3,
		heightmap = "everest.png",
		placeId = 0, -- set PlaceID in presets.go once the Place is published
	},
	["kilimanjaro"] = {
		name = "Kilimanjaro",
		continent = "Africa",
		peak = "Uhuru Peak",
		peakElevationM = 5895,
		minElevationM = 1162,
		maxElevationM = 5887,
		reliefM = 4725,
		widthM = 38887.7,
		heightM = 33392.3,
		regionSize = Vector3.new(16384, 472.5, 14068.7),
		regionPosition = Vector3.new(0, 236.3, 0),
		studsPerMeterXZ = 0.4213,
		studsPerMeterY = 0.1,
		baseElevationM = 1162,
		terrainHeightStuds = 472.5,
		verticalExaggeration = 0.2374,
		heightmap = "kilimanjaro.png",
		placeId = 0, -- set PlaceID in presets.go once the Place is published
	},
	["longspeak"] = {
		name = "Rocky Mountains",
		continent = "North America",
		peak = "Longs Peak",
		peakElevationM = 4346,
		minElevationM = 1994,
		maxElevationM = 4349,
		reliefM = 2355,
		widthM = 33970,
		heightM = 38985.4,
		regionSize = Vector3.new(16384, 471, 18802.9),
		regionPosition = Vector3.new(0, 235.5, 0),
		studsPerMeterXZ = 0.4823,
		studsPerMeterY = 0.2,
		baseElevationM = 1993.6,
		terrainHeightStuds = 471,
		verticalExaggeration = 0.4147,
		heightmap = "longspeak.png",
		placeId = 0, -- set PlaceID in presets.go once the Place is published
	},
	["montblanc"] = {
		name = "Mont Blanc",
		continent = "Europe",
		peak = "Mont Blanc",
		peakElevationM = 4810,
		minElevationM = 488,
		maxElevationM = 4790,
		reliefM = 4302,
		widthM = 38742.3,
		heightM = 38955.2,
		regionSize = Vector3.new(16384, 516.2, 16474),
		regionPosition = Vector3.new(0, 258.1, 0),
		studsPerMeterXZ = 0.4229,
		studsPerMeterY = 0.12,
		baseElevationM = 488.1,
		terrainHeightStuds = 516.2,
		verticalExaggeration = 0.2838,
		heightmap = "montblanc.png",
		placeId = 0, -- set PlaceID in presets.go once the Place is published
	},
}

-- studsToMeters converts a world Y in studs back to a real altitude in
-- metres above sea level, for the altimeter.
function Mountains.studsToMeters(m, y)
	return m.baseElevationM + y / m.studsPerMeterY
end

function Mountains.get(key)
	return Mountains.byKey[key]
end

return Mountains
