package main

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// emitLua turns the generated sidecars into a Luau module. The game reads its
// scale constants from here, so the numbers a place is built with are the ones
// the heightmap was normalised against — they cannot drift apart by hand.
func emitLua(sidecarDir, outPath string) error {
	arenas, err := loadSidecars(sidecarDir)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("-- Generated by `terrain-fetch --emit-lua`. Do not edit by hand:\n")
	b.WriteString("-- regenerate it whenever a heightmap is rebuilt, so the in-game\n")
	b.WriteString("-- scale always matches the PNG that was imported.\n--\n")
	b.WriteString("-- baseElevationM is what pure black means; every level of the 16-bit\n")
	b.WriteString("-- heightmap adds metersPerLevel. studsPerMeterY converts metres to studs.\n\n")
	b.WriteString("local Mountains = {}\n\n")
	b.WriteString("Mountains.order = {")
	for i, a := range arenas {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", a.Key)
	}
	b.WriteString("}\n\nMountains.byKey = {\n")

	for _, a := range arenas {
		s, r := a.S, a.S.Roblox
		fmt.Fprintf(&b, "\t[%q] = {\n", a.Key)
		fmt.Fprintf(&b, "\t\tname = %q,\n", s.Name)
		fmt.Fprintf(&b, "\t\tcontinent = %q,\n", s.Continent)
		fmt.Fprintf(&b, "\t\tpeak = %q,\n", s.Peak)
		fmt.Fprintf(&b, "\t\tpeakElevationM = %g,\n", s.PeakElevM)
		fmt.Fprintf(&b, "\t\tminElevationM = %g,\n", s.MinElevationM)
		fmt.Fprintf(&b, "\t\tmaxElevationM = %g,\n", s.MaxElevationM)
		fmt.Fprintf(&b, "\t\treliefM = %g,\n", s.ReliefM)
		fmt.Fprintf(&b, "\t\twidthM = %g,\n", s.WidthM)
		fmt.Fprintf(&b, "\t\theightM = %g,\n", s.HeightM)
		fmt.Fprintf(&b, "\t\tregionSize = Vector3.new(%g, %g, %g),\n",
			r.RegionSizeStuds[0], r.RegionSizeStuds[1], r.RegionSizeStuds[2])
		fmt.Fprintf(&b, "\t\tregionPosition = Vector3.new(%g, %g, %g),\n",
			r.RegionPositionStuds[0], r.RegionPositionStuds[1], r.RegionPositionStuds[2])
		fmt.Fprintf(&b, "\t\tstudsPerMeterXZ = %g,\n", r.StudsPerMeterXZ)
		fmt.Fprintf(&b, "\t\tstudsPerMeterY = %g,\n", r.StudsPerMeterY)
		fmt.Fprintf(&b, "\t\tbaseElevationM = %g,\n", r.BaseElevationM)
		fmt.Fprintf(&b, "\t\tterrainHeightStuds = %g,\n", r.TerrainHeightStuds)
		fmt.Fprintf(&b, "\t\tverticalExaggeration = %g,\n", r.VerticalExaggeration)
		fmt.Fprintf(&b, "\t\theightmap = %q,\n", s.Heightmap)
		if len(s.POIs) > 0 {
			b.WriteString("\t\tpois = {\n")
			for _, poi := range s.POIs {
				fmt.Fprintf(&b, "\t\t\t{name = %q, elevM = %g, major = %v, pos = Vector3.new(%g, %g, %g)},\n",
					poi.Name, poi.ElevM, poi.Major, poi.XStuds, poi.YStuds, poi.ZStuds)
			}
			b.WriteString("\t\t},\n")
		}
		if s.Map != nil {
			fmt.Fprintf(&b, "\t\tmap = {\n\t\t\tw = %d,\n\t\t\th = %d,\n\t\t\trows = {\n", s.Map.W, s.Map.H)
			for _, row := range s.Map.Rows {
				fmt.Fprintf(&b, "\t\t\t\t%q,\n", row)
			}
			b.WriteString("\t\t\t},\n\t\t},\n")
		}
		fmt.Fprintf(&b, "\t\tplaceId = %d, -- set PlaceID in presets.go once the Place is published\n", r.PlaceID)
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString(`-- studsToMeters converts a world Y in studs back to a real altitude in
-- metres above sea level, for the altimeter.
function Mountains.studsToMeters(m, y)
	return m.baseElevationM + y / m.studsPerMeterY
end

function Mountains.get(key)
	return Mountains.byKey[key]
end

return Mountains
`)

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d arenas)\n", outPath, len(arenas))
	return nil
}

// loadSidecars reads every terrain-fetch sidecar in a directory, sorted by key.
func loadSidecars(dir string) ([]keyedSidecar, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, err
	}
	sort.Strings(matches)
	var out []keyedSidecar
	for _, m := range matches {
		b, err := os.ReadFile(m)
		if err != nil {
			return nil, err
		}
		var s Sidecar
		if err := json.Unmarshal(b, &s); err != nil {
			return nil, fmt.Errorf("%s: %w", m, err)
		}
		if s.Generator != "terrain-fetch" {
			continue
		}
		out = append(out, keyedSidecar{strings.TrimSuffix(filepath.Base(m), ".json"), s})
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no terrain-fetch sidecars in %s", dir)
	}
	return out, nil
}

type keyedSidecar struct {
	Key string
	S   Sidecar
}

// emitImportMD writes the Studio import cheat sheet. Generated, so the numbers
// in the docs are the ones the heightmaps were actually built with.
func emitImportMD(sidecarDir, outPath string) error {
	arenas, err := loadSidecars(sidecarDir)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("<!-- Generated by `terrain-fetch --emit-import-md`. Do not edit by hand. -->\n")
	b.WriteString("# Import terenu do Roblox Studia\n\n")
	b.WriteString("Terrain Editor -> **Import**. Heightmapa je 16bit grayscale PNG,\n")
	b.WriteString("colormapa 8bit RGB. Cisla nize jsou z sidecar JSONu vedle kazde PNG.\n\n")
	b.WriteString("**Y je centrovane**: cerna = `Position.Y - Size.Y/2`, bila = `Position.Y + Size.Y/2`.\n")
	b.WriteString("Pri `Position.Y = Size.Y/2` sedi nejnizsi bod areny presne na `Y = 0`.\n\n")
	b.WriteString("| Arena | Size (study) | Position (study) | Heightmap | Vyska terenu | Prevyseni |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, a := range arenas {
		r := a.S.Roblox
		fmt.Fprintf(&b, "| %s | `%g, %g, %g` | `%g, %g, %g` | `%s` | %.0f studu (%.0f m) | %.2fx |\n",
			a.S.Name,
			r.RegionSizeStuds[0], r.RegionSizeStuds[1], r.RegionSizeStuds[2],
			r.RegionPositionStuds[0], r.RegionPositionStuds[1], r.RegionPositionStuds[2],
			a.S.Heightmap, r.TerrainHeightStuds, a.S.ReliefM, r.VerticalExaggeration)
	}

	b.WriteString("\n## Merítko\n\n")
	b.WriteString("| Arena | Vyrez | m/px | study/m vodorovne | study/m svisle | Prelet Z-V |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, a := range arenas {
		r := a.S.Roblox
		// 120 studu/s je cestovni rychlost letadla (SPEED_MAX 40 m/s x SCALE 3).
		// Vsechny areny jsou stejne siroke, takze prelet Z-V vyjde stejne.
		crossSec := r.RegionSizeStuds[0] / 120
		fmt.Fprintf(&b, "| %s | %.0f x %.0f km | %.1f | %.3f | %.2f | %.0f:%02.0f min |\n",
			a.S.Name, a.S.WidthM/1000, a.S.HeightM/1000, a.S.MetersPerPx,
			r.StudsPerMeterXZ, r.StudsPerMeterY,
			math.Floor(crossSec/60), math.Mod(crossSec, 60))
	}

	b.WriteString("\n**Prevyseni** je svisle merítko deleno vodorovnym: `1.00` = hora ma\n")
	b.WriteString("skutecne proporce, `0.30` = je splostela na tretinu. Sedi to s planem\n")
	b.WriteString("(vsechny areny ~400-600 studu vysoke), ale hory jsou tim placatejsi nez\n")
	b.WriteString("ve skutecnosti. Zvysit lze `--studs-per-meter-y`, nebo zmensit arenu\n")
	b.WriteString("pres `--arena-studs`.\n")

	b.WriteString("\n## Colormapa -> materialy\n\n")
	b.WriteString("Colormapa je natvrdo obarvena presnymi RGB vychozich `Terrain.MaterialColors`\n")
	b.WriteString("(vytazeno z `RobloxStudio.app/Contents/Resources/PlatformContent/pc/terrain/materials.json`),\n")
	b.WriteString("takze importer prirazuje materialy bez dalsiho nastavovani. Zadne prechody\n")
	b.WriteString("ani dithering - michana barva by spadla na cizi material.\n\n")
	for _, a := range arenas {
		if len(a.S.ColormapMaterials) == 0 {
			continue
		}
		fmt.Fprintf(&b, "- **%s**: ", a.S.Name)
		parts := make([]string, 0, len(a.S.ColormapMaterials))
		for _, m := range a.S.ColormapMaterials {
			if m.Percent >= 0.5 {
				parts = append(parts, fmt.Sprintf("%s %.0f%%", m.Material, m.Percent))
			}
		}
		b.WriteString(strings.Join(parts, ", ") + "\n")
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d arenas)\n", outPath, len(arenas))
	return nil
}
